export const DEPARTMENTS = [
  {
    slug: "computer-science",
    name: "Computer Science & Engineering",
    shortName: "CSE",
    hod: "Dr. Rajesh Kumar",
    hodEmail: "hod.cse@thorfinn.edu",
    hodImage: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200",
    description: "Pioneering research in AI, ML, and distributed systems.",
    students: 1200,
    faculty: 45,
    labs: ["AI Lab", "Cybersecurity Lab", "HCI Lab", "Cloud Computing Lab"],
    courses: ["B.Tech CSE", "M.Tech AI/ML", "Ph.D Computer Science", "B.Tech CSBS"],
    color: "from-blue-500 to-cyan-500",
    icon: "💻",
  },
  {
    slug: "mechanical",
    name: "Mechanical Engineering",
    shortName: "ME",
    hod: "Dr. Priya Sharma",
    hodEmail: "hod.me@thorfinn.edu",
    hodImage: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200",
    description: "Excellence in design, manufacturing, and thermal sciences.",
    students: 900,
    faculty: 38,
    labs: ["CAD/CAM Lab", "Thermal Lab", "Robotics Lab", "Materials Lab"],
    courses: ["B.Tech ME", "M.Tech Manufacturing", "Ph.D Mechanical"],
    color: "from-orange-500 to-red-500",
    icon: "⚙️",
  },
  {
    slug: "electronics",
    name: "Electronics & Communication",
    shortName: "ECE",
    hod: "Dr. Anil Verma",
    hodEmail: "hod.ece@thorfinn.edu",
    hodImage: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200",
    description: "Cutting-edge research in VLSI, IoT, and signal processing.",
    students: 850,
    faculty: 35,
    labs: ["VLSI Lab", "IoT Lab", "Signal Processing Lab", "Embedded Systems Lab"],
    courses: ["B.Tech ECE", "M.Tech VLSI", "Ph.D Electronics"],
    color: "from-green-500 to-teal-500",
    icon: "📡",
  },
  {
    slug: "civil",
    name: "Civil Engineering",
    shortName: "CE",
    hod: "Dr. Sunita Patel",
    hodEmail: "hod.ce@thorfinn.edu",
    hodImage: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200",
    description: "Building sustainable infrastructure for tomorrow.",
    students: 700,
    faculty: 30,
    labs: ["Structural Lab", "Geotechnical Lab", "Environmental Lab", "Survey Lab"],
    courses: ["B.Tech CE", "M.Tech Structural", "Ph.D Civil"],
    color: "from-yellow-500 to-amber-500",
    icon: "🏗️",
  },
  {
    slug: "mba",
    name: "Business Administration",
    shortName: "MBA",
    hod: "Dr. Vikram Singh",
    hodEmail: "hod.mba@thorfinn.edu",
    hodImage: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200",
    description: "Developing future business leaders with global perspective.",
    students: 600,
    faculty: 28,
    labs: ["Business Analytics Lab", "Finance Lab", "Marketing Studio"],
    courses: ["MBA", "Executive MBA", "Ph.D Management"],
    color: "from-purple-500 to-pink-500",
    icon: "📊",
  },
  {
    slug: "csbs",
    name: "CS & Business Systems",
    shortName: "CSBS",
    hod: "Dr. Meera Nair",
    hodEmail: "hod.csbs@thorfinn.edu",
    hodImage: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=200",
    description: "Bridging technology and business for the digital economy.",
    students: 500,
    faculty: 22,
    labs: ["Data Science Lab", "ERP Lab", "Digital Marketing Lab"],
    courses: ["B.Tech CSBS", "M.Tech Data Science"],
    color: "from-indigo-500 to-blue-500",
    icon: "🔗",
  },
];

export const STATS = [
  { label: "Students", value: "12,000+", icon: "🎓" },
  { label: "Faculty", value: "500+", icon: "👨‍🏫" },
  { label: "Research Papers", value: "2,400+", icon: "📄" },
  { label: "Placement Rate", value: "94%", icon: "💼" },
  { label: "Alumni Network", value: "50,000+", icon: "🌐" },
  { label: "Acres Campus", value: "200+", icon: "🏛️" },
];

export const PLACEMENT_COMPANIES = [
  { name: "Google", logo: "G", package: 45, sector: "Tech", hired: 12 },
  { name: "Microsoft", logo: "M", package: 42, sector: "Tech", hired: 18 },
  { name: "Amazon", logo: "A", package: 38, sector: "Tech", hired: 25 },
  { name: "Goldman Sachs", logo: "GS", package: 35, sector: "Finance", hired: 8 },
  { name: "McKinsey", logo: "Mc", package: 32, sector: "Consulting", hired: 5 },
  { name: "Infosys", logo: "I", package: 8, sector: "IT Services", hired: 120 },
  { name: "TCS", logo: "T", package: 7, sector: "IT Services", hired: 150 },
  { name: "Wipro", logo: "W", package: 7.5, sector: "IT Services", hired: 90 },
  { name: "Deloitte", logo: "D", package: 12, sector: "Consulting", hired: 35 },
  { name: "JP Morgan", logo: "JP", package: 28, sector: "Finance", hired: 10 },
  { name: "Adobe", logo: "Ad", package: 30, sector: "Tech", hired: 8 },
  { name: "Flipkart", logo: "F", package: 22, sector: "E-Commerce", hired: 15 },
];

export const NAV_LINKS = [
  { label: "About", href: "/about" },
  { label: "Academics", href: "/academics" },
  { label: "Departments", href: "/departments" },
  { label: "Research", href: "/research" },
  { label: "Admissions", href: "/admissions" },
  { label: "Placements", href: "/placements" },
  { label: "Campus Life", href: "/campus-life" },
  { label: "Alumni", href: "/alumni" },
];
