export type FacultyMember = {
  name: string;
  designation: string;
  specialization: string;
  email: string;
  img: string;
  bio: string;
  publications: number;
  experience: string;
  education: string;
};

export type LeadershipMember = {
  name: string;
  role: string;
  dept: string;
  img: string;
  bio: string;
  email: string;
  tenure: string;
};

// ── Unsplash seeds are stable — same seed always returns the same face ──

export const FACULTY: Record<string, FacultyMember> = {
  "Dr. Rajesh Kumar": {
    name: "Dr. Rajesh Kumar",
    designation: "Professor & HOD",
    specialization: "Algorithms & Complexity",
    email: "hod.cse@thorfinn.edu",
    img: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400&q=80",
    bio: "Dr. Rajesh Kumar has led the Department of Computer Science & Engineering for over a decade. His research focuses on algorithm design, computational complexity, and graph theory. He has supervised 18 PhD scholars and published 90+ papers in top-tier venues including STOC and FOCS.",
    publications: 92,
    experience: "22 years",
    education: "Ph.D, IIT Bombay · M.Tech, IIT Delhi",
  },
  "Dr. Arun Patel": {
    name: "Dr. Arun Patel",
    designation: "Professor",
    specialization: "Machine Learning",
    email: "arun.patel@thorfinn.edu",
    img: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&q=80",
    bio: "Dr. Arun Patel is a leading researcher in machine learning and deep learning. He heads the AI & ML Lab and has active collaborations with Google Research and Microsoft Research India. His work on efficient neural architecture search has been cited over 2,400 times.",
    publications: 68,
    experience: "16 years",
    education: "Ph.D, Stanford University · B.Tech, IIT Madras",
  },
  "Dr. Sneha Iyer": {
    name: "Dr. Sneha Iyer",
    designation: "Associate Professor",
    specialization: "Computer Vision",
    email: "sneha.iyer@thorfinn.edu",
    img: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&q=80",
    bio: "Dr. Sneha Iyer specialises in computer vision and medical image analysis. She leads the HCI Lab and has developed AI-assisted diagnostic tools deployed in three government hospitals. She is a recipient of the DST Women Scientist Award 2021.",
    publications: 41,
    experience: "11 years",
    education: "Ph.D, CMU · M.Tech, IIT Kharagpur",
  },
  "Dr. Ravi Shankar": {
    name: "Dr. Ravi Shankar",
    designation: "Associate Professor",
    specialization: "Distributed Systems",
    email: "ravi.shankar@thorfinn.edu",
    img: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&q=80",
    bio: "Dr. Ravi Shankar's research covers distributed computing, cloud infrastructure, and fault-tolerant systems. He has consulted for Amazon Web Services and Infosys Labs, and his open-source distributed key-value store has over 3,000 GitHub stars.",
    publications: 38,
    experience: "13 years",
    education: "Ph.D, University of Michigan · B.Tech, NIT Trichy",
  },
  "Dr. Priya Menon": {
    name: "Dr. Priya Menon",
    designation: "Assistant Professor",
    specialization: "Cybersecurity",
    email: "priya.menon@thorfinn.edu",
    img: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&q=80",
    bio: "Dr. Priya Menon leads the Cybersecurity Research Lab. Her work on zero-trust network architectures and adversarial machine learning has been published at IEEE S&P and USENIX Security. She is a certified ethical hacker and advises the CERT-In advisory board.",
    publications: 24,
    experience: "8 years",
    education: "Ph.D, Georgia Tech · M.Tech, IIT Bombay",
  },
  "Dr. Anil Verma": {
    name: "Dr. Anil Verma",
    designation: "Professor & HOD",
    specialization: "VLSI Design",
    email: "hod.ece@thorfinn.edu",
    img: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=80",
    bio: "Dr. Anil Verma is a pioneer in VLSI design and low-power chip architecture. He has filed 14 patents and collaborated with Intel and Qualcomm on next-generation SoC designs. He is a Fellow of the Indian National Academy of Engineering.",
    publications: 78,
    experience: "20 years",
    education: "Ph.D, IISc Bangalore · B.Tech, IIT Roorkee",
  },
  "Dr. Kavya Reddy": {
    name: "Dr. Kavya Reddy",
    designation: "Associate Professor",
    specialization: "Signal Processing",
    email: "kavya.reddy@thorfinn.edu",
    img: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&q=80",
    bio: "Dr. Kavya Reddy's research spans adaptive signal processing, speech recognition, and biomedical signal analysis. She has developed noise-cancellation algorithms used in hearing aid devices and holds two patents in adaptive filter design.",
    publications: 33,
    experience: "10 years",
    education: "Ph.D, IIT Madras · M.Tech, NIT Warangal",
  },
  "Dr. Suresh Babu": {
    name: "Dr. Suresh Babu",
    designation: "Assistant Professor",
    specialization: "Embedded Systems",
    email: "suresh.babu@thorfinn.edu",
    img: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&q=80",
    bio: "Dr. Suresh Babu focuses on real-time embedded systems and IoT security. He has built smart agriculture monitoring systems deployed across 200 farms in Karnataka and Tamil Nadu, funded by the Ministry of Agriculture.",
    publications: 19,
    experience: "7 years",
    education: "Ph.D, IIT Hyderabad · B.Tech, VIT Vellore",
  },
  "Dr. Nisha Thomas": {
    name: "Dr. Nisha Thomas",
    designation: "Assistant Professor",
    specialization: "RF Engineering",
    email: "nisha.thomas@thorfinn.edu",
    img: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=400&q=80",
    bio: "Dr. Nisha Thomas specialises in RF and microwave engineering with a focus on 5G antenna design and millimetre-wave communication. She has collaborated with ISRO on satellite communication antenna projects and received the Young Scientist Award from IETE.",
    publications: 21,
    experience: "6 years",
    education: "Ph.D, IIT Delhi · M.Tech, CUSAT",
  },
  "Dr. Priya Sharma": {
    name: "Dr. Priya Sharma",
    designation: "Professor & HOD",
    specialization: "Manufacturing",
    email: "hod.me@thorfinn.edu",
    img: "https://images.unsplash.com/photo-1594744803329-e58b31de8bf5?w=400&q=80",
    bio: "Dr. Priya Sharma leads the Mechanical Engineering department with expertise in advanced manufacturing and Industry 4.0. She has guided 12 PhD scholars and her research on additive manufacturing has been adopted by Tata Motors and Mahindra.",
    publications: 55,
    experience: "18 years",
    education: "Ph.D, IIT Bombay · M.Tech, IIT Kanpur",
  },
  "Dr. Arjun Das": {
    name: "Dr. Arjun Das",
    designation: "Professor",
    specialization: "Thermal Engineering",
    email: "arjun.das@thorfinn.edu",
    img: "https://images.unsplash.com/photo-1463453091185-61582044d556?w=400&q=80",
    bio: "Dr. Arjun Das is an expert in computational fluid dynamics and heat transfer. His research on waste heat recovery systems has been implemented in two industrial plants, reducing energy consumption by 18%. He is a reviewer for the International Journal of Heat and Mass Transfer.",
    publications: 47,
    experience: "15 years",
    education: "Ph.D, IIT Kharagpur · B.Tech, NIT Durgapur",
  },
  "Dr. Leela Krishnan": {
    name: "Dr. Leela Krishnan",
    designation: "Associate Professor",
    specialization: "Robotics",
    email: "leela.krishnan@thorfinn.edu",
    img: "https://images.unsplash.com/photo-1551836022-deb4988cc6c0?w=400&q=80",
    bio: "Dr. Leela Krishnan's research covers autonomous robotics, human-robot interaction, and swarm intelligence. She built the university's first autonomous robot that competed at RoboCup 2022. She is a co-founder of the Thorfinn Robotics Society.",
    publications: 29,
    experience: "9 years",
    education: "Ph.D, TU Munich · M.Tech, IIT Madras",
  },
  "Dr. Mohan Rao": {
    name: "Dr. Mohan Rao",
    designation: "Assistant Professor",
    specialization: "Materials Science",
    email: "mohan.rao@thorfinn.edu",
    img: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&q=80",
    bio: "Dr. Mohan Rao investigates nano-composite materials and their mechanical properties for aerospace and automotive applications. He has received a DST SERB Early Career Research Award and collaborates with DRDO on lightweight armour materials.",
    publications: 22,
    experience: "6 years",
    education: "Ph.D, IISc Bangalore · B.Tech, NIT Surathkal",
  },
  "Dr. Sunita Patel": {
    name: "Dr. Sunita Patel",
    designation: "Professor & HOD",
    specialization: "Structural Engineering",
    email: "hod.ce@thorfinn.edu",
    img: "https://images.unsplash.com/photo-1607746882042-944635dfe10e?w=400&q=80",
    bio: "Dr. Sunita Patel leads the Civil Engineering department with expertise in earthquake-resistant structural design. She has consulted on the structural safety of over 30 public infrastructure projects and is a member of the Bureau of Indian Standards technical committee.",
    publications: 49,
    experience: "17 years",
    education: "Ph.D, IIT Roorkee · M.Tech, IIT Delhi",
  },
  "Dr. Ramesh Gupta": {
    name: "Dr. Ramesh Gupta",
    designation: "Professor",
    specialization: "Geotechnics",
    email: "ramesh.gupta@thorfinn.edu",
    img: "https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=400&q=80",
    bio: "Dr. Ramesh Gupta is a geotechnical engineer with expertise in soil mechanics, foundation design, and slope stability. He has advised on major infrastructure projects including metro rail foundations and highway embankments across South India.",
    publications: 36,
    experience: "14 years",
    education: "Ph.D, IIT Madras · M.Tech, IIT Bombay",
  },
  "Dr. Anita Joshi": {
    name: "Dr. Anita Joshi",
    designation: "Associate Professor",
    specialization: "Environmental Engineering",
    email: "anita.joshi@thorfinn.edu",
    img: "https://images.unsplash.com/photo-1598550874175-4d0ef436c909?w=400&q=80",
    bio: "Dr. Anita Joshi's research focuses on wastewater treatment, air quality modelling, and sustainable urban infrastructure. She has developed low-cost water purification systems deployed in 15 rural communities and received the National Environmental Science Award 2020.",
    publications: 27,
    experience: "10 years",
    education: "Ph.D, IIT Kanpur · M.Tech, NIT Calicut",
  },
  "Dr. Kiran Mehta": {
    name: "Dr. Kiran Mehta",
    designation: "Assistant Professor",
    specialization: "Transportation Engineering",
    email: "kiran.mehta@thorfinn.edu",
    img: "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=400&q=80",
    bio: "Dr. Kiran Mehta specialises in traffic flow modelling, intelligent transportation systems, and road safety. He has developed simulation models used by the National Highways Authority of India for capacity planning on high-density corridors.",
    publications: 18,
    experience: "6 years",
    education: "Ph.D, IIT Delhi · B.Tech, SVNIT Surat",
  },
  "Dr. Vikram Singh": {
    name: "Dr. Vikram Singh",
    designation: "Professor & HOD",
    specialization: "Business Strategy",
    email: "hod.mba@thorfinn.edu",
    img: "https://images.unsplash.com/photo-1556157382-97eda2d62296?w=400&q=80",
    bio: "Dr. Vikram Singh is a strategy scholar with industry experience at McKinsey & Company. His research on competitive dynamics in emerging markets has been published in the Strategic Management Journal and Harvard Business Review. He advises three listed companies on their boards.",
    publications: 44,
    experience: "19 years",
    education: "Ph.D, INSEAD · MBA, IIM Ahmedabad",
  },
  "Dr. Pooja Kapoor": {
    name: "Dr. Pooja Kapoor",
    designation: "Professor",
    specialization: "Finance",
    email: "pooja.kapoor@thorfinn.edu",
    img: "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=400&q=80",
    bio: "Dr. Pooja Kapoor is a finance scholar specialising in corporate governance, capital markets, and ESG investing. She previously worked at SEBI and brings deep regulatory expertise to her teaching. Her research has been cited in RBI policy documents.",
    publications: 31,
    experience: "13 years",
    education: "Ph.D, IIM Calcutta · CA, ICAI",
  },
  "Dr. Sanjay Mishra": {
    name: "Dr. Sanjay Mishra",
    designation: "Associate Professor",
    specialization: "Marketing",
    email: "sanjay.mishra@thorfinn.edu",
    img: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=400&q=80",
    bio: "Dr. Sanjay Mishra's research covers consumer behaviour, digital marketing, and brand management. He has consulted for Hindustan Unilever and Nestlé India on brand strategy and has developed a widely-used consumer sentiment analysis framework.",
    publications: 26,
    experience: "11 years",
    education: "Ph.D, IIM Bangalore · MBA, XLRI Jamshedpur",
  },
  "Dr. Ritu Agarwal": {
    name: "Dr. Ritu Agarwal",
    designation: "Assistant Professor",
    specialization: "Operations Management",
    email: "ritu.agarwal@thorfinn.edu",
    img: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&q=80",
    bio: "Dr. Ritu Agarwal focuses on supply chain optimisation, lean operations, and healthcare operations management. She has worked with Apollo Hospitals on patient flow optimisation and published in the Journal of Operations Management.",
    publications: 17,
    experience: "7 years",
    education: "Ph.D, IIM Lucknow · B.Tech, DTU Delhi",
  },
  "Dr. Meera Nair": {
    name: "Dr. Meera Nair",
    designation: "Professor & HOD",
    specialization: "Data Science",
    email: "hod.csbs@thorfinn.edu",
    img: "https://images.unsplash.com/photo-1614644147798-f8c0fc9da7f6?w=400&q=80",
    bio: "Dr. Meera Nair bridges computer science and business analytics. She leads the Data Science & Analytics Lab and has developed predictive models for financial fraud detection used by two private sector banks. She is a Google Women Techmakers Scholar mentor.",
    publications: 39,
    experience: "14 years",
    education: "Ph.D, IIT Bombay · MBA, IIM Kozhikode",
  },
  "Dr. Ajay Pillai": {
    name: "Dr. Ajay Pillai",
    designation: "Associate Professor",
    specialization: "Business Intelligence",
    email: "ajay.pillai@thorfinn.edu",
    img: "https://images.unsplash.com/photo-1504257432389-52343af06ae3?w=400&q=80",
    bio: "Dr. Ajay Pillai specialises in business intelligence, data warehousing, and enterprise analytics. He has implemented BI solutions for three Fortune 500 companies and teaches the university's flagship Business Analytics course.",
    publications: 22,
    experience: "9 years",
    education: "Ph.D, IIT Hyderabad · M.Tech, NIT Calicut",
  },
  "Dr. Swati Verma": {
    name: "Dr. Swati Verma",
    designation: "Assistant Professor",
    specialization: "ERP Systems",
    email: "swati.verma@thorfinn.edu",
    img: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&q=80",
    bio: "Dr. Swati Verma is an SAP-certified consultant and researcher in enterprise resource planning and digital transformation. She has led ERP implementation projects at two manufacturing firms and her research on ERP adoption in SMEs is widely cited.",
    publications: 14,
    experience: "6 years",
    education: "Ph.D, IIM Indore · MBA, Symbiosis Pune",
  },
  "Dr. Nikhil Jain": {
    name: "Dr. Nikhil Jain",
    designation: "Assistant Professor",
    specialization: "Digital Marketing",
    email: "nikhil.jain@thorfinn.edu",
    img: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=400&q=80",
    bio: "Dr. Nikhil Jain's research covers social media analytics, influencer marketing, and e-commerce strategy. He previously worked at Flipkart's growth team and brings practical industry experience to his courses on digital business models.",
    publications: 12,
    experience: "5 years",
    education: "Ph.D, IIT Bombay · MBA, IIM Shillong",
  },
};

export const LEADERSHIP: Record<string, LeadershipMember> = {
  "Prof. Arjun Mehta": {
    name: "Prof. Arjun Mehta",
    role: "Vice Chancellor",
    dept: "Office of the Vice Chancellor",
    img: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400&q=80",
    bio: "Prof. Arjun Mehta has served as Vice Chancellor since 2018, steering the university through its most transformative decade. Under his leadership, Thorfinn achieved NAAC A++ accreditation, launched the AI Research Institute, and grew its research output by 60%. He holds a Ph.D from MIT and was previously Dean of Engineering at IIT Delhi.",
    email: "vc@thorfinn.edu",
    tenure: "2018 – Present",
  },
  "Dr. Kavitha Rao": {
    name: "Dr. Kavitha Rao",
    role: "Pro Vice Chancellor",
    dept: "Academic Affairs",
    img: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&q=80",
    bio: "Dr. Kavitha Rao oversees all academic programs, curriculum development, and faculty affairs. She has spearheaded the introduction of interdisciplinary programs and the university's NEP 2020 implementation. She holds a Ph.D in Education Policy from the University of Edinburgh.",
    email: "pvc@thorfinn.edu",
    tenure: "2020 – Present",
  },
  "Prof. Suresh Nair": {
    name: "Prof. Suresh Nair",
    role: "Dean of Academics",
    dept: "Academic Programs",
    img: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=80",
    bio: "Prof. Suresh Nair manages the academic calendar, examination systems, and program accreditation. He has over 25 years of experience in higher education administration and has been instrumental in establishing the university's credit transfer framework with 12 international universities.",
    email: "dean.academics@thorfinn.edu",
    tenure: "2016 – Present",
  },
  "Dr. Ananya Singh": {
    name: "Dr. Ananya Singh",
    role: "Dean of Research",
    dept: "Research & Innovation",
    img: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&q=80",
    bio: "Dr. Ananya Singh leads the university's research strategy, managing ₹45 Cr in active research grants. She has established partnerships with DRDO, DST, and ISRO, and oversees the Innovation & Entrepreneurship Centre that has incubated 100+ startups.",
    email: "dean.research@thorfinn.edu",
    tenure: "2019 – Present",
  },
  "Dr. Vikram Patel": {
    name: "Dr. Vikram Patel",
    role: "Dean of Students",
    dept: "Student Affairs",
    img: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&q=80",
    bio: "Dr. Vikram Patel is responsible for student welfare, hostel administration, placement coordination, and extracurricular activities. He introduced the peer mentorship programme that has improved first-year retention rates by 22% and oversees the university's mental health initiative.",
    email: "dean.students@thorfinn.edu",
    tenure: "2017 – Present",
  },
  "Prof. Meera Iyer": {
    name: "Prof. Meera Iyer",
    role: "Registrar",
    dept: "Administration",
    img: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&q=80",
    bio: "Prof. Meera Iyer manages all administrative, legal, and statutory functions of the university. She has digitised the university's entire records system, reducing administrative processing time by 40%, and oversees compliance with UGC and AICTE regulations.",
    email: "registrar@thorfinn.edu",
    tenure: "2015 – Present",
  },
};
